---
- hosts: all
  become: yes
  tasks:
  - name: assert we are deploying to a raspberry pi
    assert:
      that:
       - ansible_lsb.id == "Raspbian"

  - name: check out the git repo
    git:
      repo: "https://github.com/blinken/paradar.git"
      dest: /opt/paradar
    tags: git

  - name: update all debian packages
    apt:
      upgrade: dist
      update_cache: yes
      dpkg_options: 'force-confold,force-confdef'
    tags: apt

  - name: Install Debian dependencies
    apt:
      pkg:
      - bind9-host
      - chrony
      - firmware-brcm80211
      - firmware-misc-nonfree
      - firmware-realtek
      - gpsd
      - libbladerf1
      - librtlsdr-dev
      - librtlsdr0
      - libtinfo6
      - lighttpd
      - openssh-client
      - openssh-server
      - python
      - python-apt
      - python3
      - python3-apt
      - python3-pip
      - vim
      - xz-utils
    tags: apt

  - name: Remove unneeded Debian packages
    apt:
      state: absent
      purge: yes
      autoremove: yes
      autoclean: yes
      pkg:
      - adwaita-icon-theme
      - alsa-utils
      - avahi-daemon
      - bluez
      - build-essential
      - dbus
      - gtk-update-icon-cache
      - hicolor-icon-theme
      - python-virtualenv
      - python3-virtualenv
      - raspi-config
      - triggerhappy
      - x11-common
    tags: apt

  - name: Install distributed dump1090-flightaware package
    apt:
      deb: "/opt/paradar/dist/dump1090-fa/{{item}}"
    with_items:
      - dump1090_3.8.0_all.deb
      - dump1090-fa_3.8.0_armhf.deb
    tags: apt

  - name: install virtualenv package to system pip
    pip:
      executable: pip3
      name: virtualenv
    tags: python

  - name: install paradar requirements to virtual environment
    pip:
      requirements: /opt/paradar/requirements.txt
      virtualenv: /opt/paradar
      virtualenv_python: /usr/bin/python4
    tags: python

  - name: install systemd unit file
    copy:
      src: ../../system/paradar.service
      dest: /etc/systemd/system/paradar.service
      owner: root
      group: root
      mode: 0644
    tags: system

  - name: install gpsd config file
    copy:
      src: ../../system/default.gpsd
      dest: /etc/default/gpsd
      owner: root
      group: root
      mode: 0644
    tags: system

  - name: ask systemd to reload config
    systemd:
      daemon_reload: yes
    tags: system

  - name: restart gpsd
    systemd:
      name: gpsd
      state: restarted
    tags: system
