---
- hosts: all
  become: yes
  tasks:
  - name: assert we are deploying to a raspberry pi
    assert:
      that:
       - ansible_lsb.id == "Raspbian"

  - name: ensure we're mounted read-write
    mount:
      opts: rw
      state: remounted
      path: "{{ item }}"
    with_items:
      - /
      - /boot
    changed_when: false

  - name: remove default user
    user:
      name: pi
      state: absent
      remove: yes
    tags: system

  - name: create admin user
    user:
      name: blinken
      comment: Paradar admin
      uid: 1001
      group: adm
      groups: sudo,audio,video,plugdev,users,input,netdev,spi,i2c,gpio
      update_password: always
      password: "$6$dbTCVDJCXt0PRaCd$ipa64clklUjHNQdemX71xgkJgvtwsp/sG6/tNzKYF89nF8ygSAaK99/z64BbjgUbHzbm6OTPyVw6GtUoOznFl0"
    tags: system

  - name: check out the git repo
    git:
      repo: "https://github.com/blinken/paradar.git"
      dest: /opt/paradar
    tags: git

  - name: update all debian packages
    apt:
      upgrade: dist
      update_cache: yes
      dpkg_options: 'force-confold,force-confdef'
    tags: apt

  - name: Install Debian dependencies
    apt:
      pkg:
      - bind9-host
      - busybox-syslogd
      - chrony
      - dnsmasq
      - ferm
      - firmware-brcm80211
      - firmware-misc-nonfree
      - firmware-realtek
      - gpsd
      - hostapd
      - libbladerf1
      - librtlsdr-dev
      - librtlsdr0
      - libtinfo6
      - lighttpd
      - openssh-client
      - openssh-server
      - python
      - python-apt
      - python3
      - python3-apt
      - python3-pip
      - vim
      - xz-utils
    tags: apt

  - name: Remove unneeded Debian packages
    apt:
      state: absent
      purge: yes
      autoremove: yes
      autoclean: yes
      pkg:
      - adwaita-icon-theme
      - alsa-utils
      - avahi-daemon
      - bluez
      - build-essential
      - dbus
      - gtk-update-icon-cache
      - hicolor-icon-theme
      - python-virtualenv
      - python3-virtualenv
      - raspi-config
      - rsyslogd
      - triggerhappy
      - x11-common
    tags: apt

  - name: Install distributed dump1090-flightaware package
    apt:
      deb: "/opt/paradar/dist/dump1090-fa/{{item}}"
    with_items:
      - dump1090_3.8.0_all.deb
      - dump1090-fa_3.8.0_armhf.deb
    tags: apt

  - name: install virtualenv package to system pip
    pip:
      executable: pip3
      name: virtualenv
    tags: python

  - name: install paradar requirements to virtual environment
    pip:
      requirements: /opt/paradar/requirements.txt
      virtualenv: /opt/paradar
      virtualenv_python: /usr/bin/python4
    tags: python

  - name: install /etc/
    copy:
      src: "../../system/etc.{{ item }}"
      dest: "/etc/{{ item }}"
      owner: root
      group: root
      mode: 0644
    with_items:
      - hosts
      - hostname
      - motd
    tags: system

  - name: install defaults files
    copy:
      src: "../../system/default.{{ item }}"
      dest: "/etc/default/{{ item }}"
      owner: root
      group: root
      mode: 0644
    with_items:
      - ferm
      - gpsd
      - console-setup
      - busybox-syslogd
    tags: system

  - name: install hostapd config
    copy:
      src: "../../system/etc.hostapd.{{ item }}"
      dest: "/etc/hostapd/{{ item }}"
      owner: root
      group: root
      mode: 0644
    with_items:
      - hostapd.wpa_psk
      - hostapd.conf
    tags: system

  - name: install wpa_supplicant config
    copy:
      src: "../../system/etc.wpa_supplicant.conf"
      dest: "/etc/wpa_supplicant/wpa_supplicant.conf"
      owner: root
      group: root
      mode: 0644
    tags: system

  - name: install /etc/ssh/sshd_config
    copy:
      src: "../../system/etc.ssh.sshd_config"
      dest: "/etc/ssh/sshd_config"
      owner: root
      group: root
      mode: 0644
    tags: system

  - name: clear SSH host keys
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /etc/ssh/ssh_host_dsa_key
      - /etc/ssh/ssh_host_dsa_key.pub
      - /etc/ssh/ssh_host_ecdsa_key
      - /etc/ssh/ssh_host_ecdsa_key.pub
      - /etc/ssh/ssh_host_ed25519_key
      - /etc/ssh/ssh_host_ed25519_key.pub
      - /etc/ssh/ssh_host_rsa_key
      - /etc/ssh/ssh_host_rsa_key.pub
    tags: system

  - name: install /etc/ferm/ferm.conf
    copy:
      src: "../../system/etc.ferm.conf"
      dest: "/etc/ferm/ferm.conf"
      owner: root
      group: root
      mode: 0644
    tags: system

  - name: install chrony config file
    copy:
      src: ../../system/chrony.conf
      dest: /etc/chrony/chrony.conf
      owner: root
      group: root
      mode: 0644
    tags: system

  - name: ensure certain kernel modules are loaded at boot
    lineinfile:
      path: /etc/modules
      line: "{{ item }}"
    with_items:
      - pps_ldisc
      - hostap
    tags: system

  - name: install boot configuration
    copy:
      src: "../../system/{{ item }}"
      dest: "/boot/{{ item }}"
      owner: root
      group: root
      mode: 0755
    with_items:
      - cmdline.txt
      - config.txt
    tags: system

  - name: install fstab
    copy:
      src: ../../system/fstab
      dest: /etc/fstab
      owner: root
      group: root
      mode: 0644
    tags: system

  - name: install sudoers
    copy:
      src: ../../system/sudoers
      dest: /etc/sudoers
      owner: root
      group: root
      mode: 0440
    tags: system

  - name: disable dump1090, lighttpd, swapfile and various other unneeded services
    systemd:
      name: "{{ item }}"
      state: stopped
      enabled: no
    with_items:
      - lighttpd
      - dump1090-fa
      - dphys-swapfile
      - keyboard-setup
      - apt-daily
      - logrotate.timer
      - man-db.timer
      - apt-daily-upgrade.timer
      - apt-daily.timer
      - systemd-tmpfiles-setup.service
      - systemd-update-utmp.service
      - systemd-rfkill.service
      - hostapd
      - dnsmasq
    tags: system

  - name: install systemd unit files
    copy:
      src: "../../system/{{ item }}"
      dest: "/etc/systemd/system/{{ item }}"
      owner: root
      group: root
      mode: 0644
    with_items:
      - systemd.paradar.service
      - systemd.paradar-logs.service
      - systemd.paradar-keys.service
      - systemd.paradar-logs.timer
      - systemd.random-seed.service
    tags: system

  - name: ask systemd to reload config
    systemd:
      daemon_reload: yes
    tags: system

  - name: restart services
    systemd:
      name: "{{ item }}"
      enabled: yes
      state: restarted
    with_items:
      - gpsd
      - chrony
      - paradar
      - paradar-logs
      - paradar-keys
    tags: system

  - name: ensure temporary directories are unmounted
    mount:
      state: unmounted
      path: "{{ item }}"
    with_items:
      - /tmp
      - /var/tmp
      - /var/log
      - /var/spool
      - /var/lib/dhcp
      - /var/lib/dhcpcd5
    tags: system

  - name: clear ephemeral files and directories
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /tmp
      - /var/tmp
      - /var/log
      - /var/lib/dhcp
      - /var/lib/dhcpcd5
      - /var/spool
      - /var/lib/systemd/random-seed
    tags: system

  - name: recreate temporary directories
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0644
    with_items:
      - /tmp
      - /var/tmp
      - /var/log
      - /var/lib/dhcp
      - /var/lib/dhcpcd5
      - /var/spool
    tags: system

  - name: create storage partition
    file:
      path: /storage
      state: directory
    tags: system

  - name: create ephemeral random seed
    file:
      path: /var/lib/systemd/random-seed
      src: /tmp/random-seed
      state: link
      force: yes
    tags: system

  - name: create ro/rw binaries
    copy:
      src: "../../system/bin.{{ item }}"
      dest: "/bin/{{ item }}"
      owner: root
      group: root
      mode: 0755
    with_items:
      - ro
      - rw
    tags: system
